### ISSUE TITLE
와이어프레임-로그인

### ISSUE THREAD

**Issue by bb-grizzle** [mash-up-kr/luvket#14]
사용자 로그인
- sns 로그인(카카오톡, 페이스북)
https://zpl.io/boGoe4M

**Comment by jus0k** [comment]
한글로 해주시면 안되나요? (예를 들어 페이스북으로 시작하기, 카카오톡으로 시작하기)

**Comment by chayeoi** [comment]
특별한 이슈사항 없습니다.

**Comment by bb-grizzle** [comment]
> 한글로 해주시면 안되나요? (예를 들어 페이스북으로 시작하기, 카카오톡으로 시작하기)

네 그렇게 하도록 할게요.

**Comment by bb-grizzle** [comment]
@jus0k 수정했습니다.

**Comment by jus0k** [comment]
수정 사항 확인했습니다! 이상 없습니다.

**Comment by sdh2398** [comment]
이상없습니다

**Comment by vo0a** [comment]
이상 없습니다.

**Comment by yurim22** [comment]
이상없습니다
