### ISSUE TITLE
와이어프레임-프로필설정

### ISSUE THREAD

**Issue by bb-grizzle** [mash-up-kr/luvket#15]
회원가입 후 프로필 설정 페이지 입니다. 
- sns로 프로필 사진과 이름 가져오기
- 사진을 설정할 수 있습니다.
- 이름을 설정할 수 있습니다.

https://zpl.io/amwO0DD

**Comment by yurim22** [comment]
초기설정은 sns에서 가져온 프로필 사진과 이름으로 되어있고, 사용자가 수정가능할 수 있게 하는건가요??

**Comment by bb-grizzle** [comment]
> 초기설정은 sns에서 가져온 프로필 사진과 이름으로 되어있고, 사용자가 수정가능할 수 있게 하는건가요??

@yurim22 네 맞습니다.

**Comment by rohi404** [comment]
user id 누르면 아이디 변경 가능한가요?

**Comment by chayeoi** [comment]
"나와 함께 약속을 지켜나갈 연인을 초대해주세요."라는 문구에서 "지켜나갈"이라는 워딩은 럽킷리스트에 작성한 모든 항목은 **언젠간 반드시 지켜야한다**라는 느낌을 주는 듯 합니다. 이런 느낌보다는 **흘려보낼 수도 있었던 약속들을 럽킷리스트에 기록하고 시간이 생겼을 때 꺼내볼 수 있다**는 느낌으로 다듬으면 좋을  것 같습니다.

**Comment by bb-grizzle** [comment]
> user id 누르면 아이디 변경 가능한가요?

@rohi404 불러온 영역이 텍스트 박스형식으로 될 것 같아요

**Comment by bb-grizzle** [comment]
@chayeoi 워딩은 확실히 정한게 아니라 나중에 수정해도 되지 않을까요?

**Comment by jus0k** [comment]
특별한 이슈 사항 없습니다~

**Comment by vo0a** [comment]
이상 없습니다

**Comment by yurim22** [comment]
이상없습니다.

**Comment by sdh2398** [comment]
이상 없습니다
