### ISSUE TITLE
와이어프레임-초대

### ISSUE THREAD

**Issue by bb-grizzle** [mash-up-kr/luvket#16]
자신과 함께 약속을 만들어갈 사람을 초대할 수 있습니다.
- 카카오톡으로 초대하기
- 문자로 초대하기
- 링크 복사하기 > 클립보드에 복사

초대 보내기: https://zpl.io/V4dZ7EQ
초대 대기: https://zpl.io/amwO08e
초대 받기: https://zpl.io/adw40xn

링크복사는 없어도 되지 않을까 생각이 듭니다.

**Comment by jus0k** [comment]
문자로 초대하기는 돈이 드는 서비스라 일단은 빼도 좋을 것 같아요!

**Comment by bb-grizzle** [comment]
> 문자로 초대하기는 돈이 드는 서비스라 일단은 빼도 좋을 것 같아요!

@jus0k 어케이

**Comment by chayeoi** [comment]
> 문자로 초대하기는 돈이 드는 서비스라 일단은 빼도 좋을 것 같아요!

동의합니다~

**Comment by chayeoi** [comment]
1. "카카오톡으로 초대하기" 버튼 클릭 시 발생하는 액션에 대해 설명해주실 수 있나요?
2. 초대가 완료되고 난 후, 현재 화면으로 돌아오고 난 후 명시적으로 완료 버튼을 눌러야만 절차를 완료할 수 있는건가요? 초대를 성공적으로 수행한 경우 자동으로 절차가 완료되도록 해도 좋을 것 같습니다. 그렇게 한다면 완료 버튼은 아예 빼도 될 것 같네요~

**Comment by bb-grizzle** [comment]
@chayeoi 
01. 카카오톡 초대하기 했을때 카카오톡에서 링크를 전달할 수 있게 해주시면 될것 같아요. 이부분은 주성이가 잘 알고 있을거에요! @jus0k 

02. 이부분은 얘기를 조금 하면 좋을것 같아요. 저도 서로 확인했을때 들어가는 프로세스를 확실히 몰라서 얘기를 해보면 좋을 것 같습니다.

**Comment by yurim22** [comment]
초대를 받은 사람이 서비스 최초 이용자일 경우, 첫번째 'signin' 화면으로 접속되고 로그인 및 프로필 설정 후 **"invite"** (초대하기) 화면이 필요 없을 것 같은데, 이럴 경우에는 바로 **"invite-reply"** 화면으로 넘어가는 건가요??

**Comment by bb-grizzle** [comment]
@yurim22 그럴것 같아요! 초대 받고 들어가는 사용자도 회원가입, 프로필 설정 후 가면 될것 같아요!

**Comment by bb-grizzle** [comment]
초대하기 부분 수정했어요! 
사용자가 초대한 후 환영 페이지로 이동되면 될 것 같아요! 

환영 페이지: https://zpl.io/bLnjQLQ
- 팝업 형식일것 같은데 아직 워딩은 구체적이지 않아요!

초대 받았을 때 이미 다른사람과 연결되어 있을 경우 중복으로 인한 실패를 보여주고 설정으로 이동시켜 주면 될 것 같아요.
중복실패: https://zpl.io/adw4JRp
- 내용은 수정가능합니다.

**Comment by jus0k** [comment]
@bb-grizzle 초대하기 링크를 보내고 아직 상대방이 수락하지 않은 경우에 기다리라는 내용의 화면은 따로 필요 없을까요?

**Comment by vo0a** [comment]
@bb-grizzle 초대받기에서 '거절'누르면 어떻게 되나요?

**Comment by bb-grizzle** [comment]
@jus0k 초대가 완료되지 않아도 개인으로 사용할 수 있도록 했습니다!

**Comment by bb-grizzle** [comment]
@vo0a 거절했을때 초대 보낸 사람은 알람을 따로 줘야 할 것 같은데 아직 그부분은 확실히 잡히진 않았어요!

**Comment by sdh2398** [comment]
나중에 하기 하면 그냥 홈화면으로 가는거에요?

**Comment by bb-grizzle** [comment]
@sdh2398 네 맞습니다!

**Comment by chayeoi** [comment]
@bb-grizzle 초대를 하면
