### ISSUE TITLE
와이어프레임-홈

### ISSUE THREAD

**Issue by bb-grizzle** [mash-up-kr/luvket#18]
- 검색
- 리스트 편집
- 리스트 뷰 변경
- 리스트 체크
- 리스트 추가하기

https://zpl.io/V0je1Po

**Comment by jus0k** [comment]
타이틀, 태그 구분하는 박스는 검색바와 관련 있는 기능이고, 카테고리와 정렬은 선택되면 바로 뷰가 바뀌는 화면이라 두 개의 구분이 되어 있는 편이 좋을 것 같다는 생각이 듭니다!

**Comment by jus0k** [comment]
이상 없습니다~

**Comment by yurim22** [comment]
이상없습니다.

**Comment by vo0a** [comment]
![view 변경 아이콘](https://user-images.githubusercontent.com/44438366/69476184-f6742700-0e19-11ea-81a9-47ae4a3696a7.jpg)
@bb-grizzle 리스트 뷰 변경 아이콘 이런식으로 하는 건 어떤가요? 그냥 '변경'은 뭘 변경하라는건지 눌러보기 전까진 잘 모를것 같아요.

**Comment by jus0k** [comment]
> ![view 변경 아이콘](https://user-images.githubusercontent.com/44438366/69476184-f6742700-0e19-11ea-81a9-47ae4a3696a7.jpg)
> @bb-grizzle 리스트 뷰 변경 아이콘 이런식으로 하는 건 어떤가요? 그냥 '변경'은 뭘 변경하라는건지 눌러보기 전까진 잘 모를것 같아요.

동의합니다!

**Comment by bb-grizzle** [comment]
@vo0a @jus0k 위치만 잡아놓은거고 텍스트로 버튼 만든다는 뜻이 아니였어요!! 반영하도록 하겠습니다.

**Comment by sdh2398** [comment]
링크 잘못됐어요

**Comment by bb-grizzle** [comment]
@sdh2398 다시 수정했어요! 변경된듯!
