### ISSUE TITLE
와이어프레임-홈/필터링

### ISSUE THREAD

**Issue by bb-grizzle** [mash-up-kr/luvket#19]
홈에서 리스트를 필터링 할 수 있습니다. 

필터링: https://zpl.io/V0je1Po
필터링 보기: https://zpl.io/aBpm8j0
필터링 활성화: https://zpl.io/aX1LNGx

페러런스: 네이버 쇼핑

**Comment by jus0k** [comment]
타이틀, 태그 구분하는 박스는 검색바와 관련 있는 기능이고, 카테고리와 정렬은 선택되면 바로 뷰가 바뀌는 화면이라 두 개의 구분이 되어 있는 편이 좋을 것 같다는 생각이 듭니다!

**Comment by bb-grizzle** [comment]
> 타이틀, 태그 구분하는 박스는 검색바와 관련 있는 기능이고, 카테고리와 정렬은 선택되면 바로 뷰가 바뀌는 화면이라 두 개의 구분이 되어 있는 편이 좋을 것 같다는 생각이 듭니다!

동의합니다.

**Comment by bb-grizzle** [comment]
@jus0k 검색 설정은 검색창이랑 합쳤어요! 수정했습니다

**Comment by jus0k** [comment]
수정 확인했습니다~ home 에는 반영이 되어 있는데 home_filter, home_filter_active에도 반영이 필요할 것 같습니다!

**Comment by vo0a** [comment]
이상 없습니다.

**Comment by bb-grizzle** [comment]
@jus0k 네네 나머지도 수정 되었어요!
