### ISSUE TITLE
와이어프레임-홈/오늘일정

### ISSUE THREAD

**Issue by bb-grizzle** [mash-up-kr/luvket#20]
오늘 일정이 있을 경우 알림을 줍니다.

https://zpl.io/bWnKEBe

**Comment by jus0k** [comment]
일정 확인하는 박스의 위치가 중간에 있어서 리스트 전체가 밀리는 것 보다는 Material Component에 Snackbar 같은 형태가 구현하기 더 쉽고 명확할 것 같다는 생각이 드는데 어떠신가요? 
https://material.io/components/snackbars/#

**Comment by bb-grizzle** [comment]
@jus0k 찬성찬연

**Comment by jus0k** [comment]
https://material.io/components/banners/
로 가고 버튼 2개로 하기로 함!

**Comment by vo0a** [comment]
@bb-grizzle 숨기기가 두 개 입니다.

**Comment by bb-grizzle** [comment]
@vo0a 수정되었습니다!
