### ISSUE TITLE
와이어프레임-홈/편집

### ISSUE THREAD

**Issue by bb-grizzle** [mash-up-kr/luvket#21]
홈에서 리스트를 일괄 편집 할 수 있습니다.

편집 선택: https://zpl.io/2E9q068
편집 리스트: https://zpl.io/aNnZQGv
편집 >삭제: https://zpl.io/VKLpzAJ
편집>완료: https://zpl.io/adw40AR

삭제> 리스트를 삭제 합니다.
확인> 리스트를 완료로 바꿉니다.

**Comment by jus0k** [comment]
편집에서 버킷리스트의 완료 여부와 삭제를 일괄으로 처리할 수 있다는 걸 모를 수도 있을 것 같아요. 편집을 누르면  list_detail_menu 화면 처럼 '일괄 완료 처리하기', '일괄 삭제하기' 라는 버튼 두 개가 뜨고 먼저 선택한 후 처리를 하는게 어떨까요?

**Comment by bb-grizzle** [comment]
@jus0k 큰 문제 없을 것 같은데 개발적으로 더 번거롭지 않나요? 상관없다면 그렇게 진행하도록 할게요1

**Comment by jus0k** [comment]
@bb-grizzle 우측 상단의 '완료'와 우측 하단의 '확인'이라는 단어가 모호해서 사용자 입장에서 혼동이 있을 것 같아 제안드렸습니다! 개발적으로는 크게 문제 없을 것 같습니다~

**Comment by bb-grizzle** [comment]
@jus0k okok 수정하겠어요!

**Comment by chayeoi** [comment]
> 편집에서 버킷리스트의 완료 여부와 삭제를 일괄으로 처리할 수 있다는 걸 모를 수도 있을 것 같아요. 편집을 누르면 list_detail_menu 화면 처럼 '일괄 완료 처리하기', '일괄 삭제하기' 라는 버튼 두 개가 뜨고 먼저 선택한 후 처리를 하는게 어떨까요?

위 내용 확인했고 이 부분에 대한 이슈사항은 없습니다.

**Comment by chayeoi** [comment]
아이템을 선택할 수 있는 화면에서 여러 개를 선택할 수 있다는 정보를 확실히 전달하기 위해서 실제 시안에서는  라디오버튼을 체크박스로 변경하면 좋을 것 같습니다.
그 외 특별한 이슈사항 없습니다.

**Comment by bb-grizzle** [comment]
@chayeoi 네 확인했습니다! 반영할게요!

**Comment by chayeoi** [comment]
디자인 시안 작업 들어간 와이어프레임 작업은 모두 close하겠습니다.
