### ISSUE TITLE
와이어프레임-뷰 변경

### ISSUE THREAD

**Issue by bb-grizzle** [mash-up-kr/luvket#22]
홈에서 리스트 뷰를 변경할 수 있습니다.

https://zpl.io/2vo1pBe

**Comment by vo0a** [comment]
![view 변경 아이콘](https://user-images.githubusercontent.com/44438366/69476327-f9701700-0e1b-11ea-9199-007207e45fa9.jpg)

@bb-grizzle 변경 버튼 위 처럼 하는 건 어떤가요?
