### ISSUE TITLE
와이어프레임-리스트/상세보기

### ISSUE THREAD

**Issue by bb-grizzle** [mash-up-kr/luvket#23]
리스트를 상세히 볼 수 있다.

https://zpl.io/Vq5mg67

**Comment by jus0k** [comment]
리스트 상세 보기의 메뉴와 홈 화면의 메뉴가 지금은 텍스트로만 되어 있어서 동일한 버튼처럼 보일 수 있을 것 같은데 확실히 구분이 되는 모양이면 좋을 것 같습니다! 예를 들어 홈 화면의 메뉴는 햄버거, 디테일의 메뉴는 ... (알아서 잘 해주실 것이지만 혹시 리뷰하시는 분들이 헷갈릴 수 있을 것 같아서 리뷰 남깁니다 🙂)

**Comment by bb-grizzle** [comment]
@jus0k 네네 알겠습니다.
