### ISSUE TITLE
와이어프레임-리스트 추가

### ISSUE THREAD

**Issue by bb-grizzle** [mash-up-kr/luvket#24]
사진 추가: https://zpl.io/bWnKE1p
- 엘범> 앨범에서 사진을 추가할 수 있다.
- 사진> 사진을 바로 촬영해서 사진을 추가할 수 있다.

상세 입력: https://zpl.io/VYnw4Jm
- 카테고리
- 제목
- 메모
- 장소
- 태그
- 나만보기

**Comment by jus0k** [comment]
사진 추가 화면에서 이미 카메라가 켜져있는 화면인데 사진 버튼이 또 있는게 어색한 것 같습니다! 상단에 생략 버튼을 아래로 가져와서 '앨범에서 선택하기', '넘어가기' 2개의 버튼이 있는게 어떨까요?

**Comment by jus0k** [comment]
상세 입력 화면에서 각각의 필드의 레이블이 있어야 입력할 때도 사용자가 어떤 것을 입력하고 있었던 것인지 헷갈리지가 않은 것 같다는 생각이 듭니다! Placeholder로 있던 Label(제목, 메모 등)이 사용자가 입력할 때도 확인할 수 있도록 Label과 Placeholder를 구분하거나 별도의 애니메이션 처리 (Material의 Text Field 컴포넌트)가 필요할 것 같습니다!

**Comment by rohi404** [comment]
상세 입력 화면에서 사용자가 앨범에 있는 사진을 다시 선택할수도 있으므로 '다시찍기' 보다는 '다시 가져오기' 나 다른 문구가 좋을것 같습니다!

**Comment by yurim22** [comment]
오른쪽 윗 부분에 생략 버튼 대신에 '다음'이라는 버튼을 넣고
사진 촬영 후 다시 찍고싶을 경우 현재 페이지에서 다시 찍을 수 있게 하는게 좋지않을까요??

**Comment by bb-grizzle** [comment]
> 사진 추가 화면에서 이미 카메라가 켜져있는 화면인데 사진 버튼이 또 있는게 어색한 것 같습니다! 상단에 생략 버튼을 아래로 가져와서 '앨범에서 선택하기', '넘어가기' 2개의 버튼이 있는게 어떨까요?

@jus0k 동의함 수정하도록 하겠어요.

**Comment by bb-grizzle** [comment]
> 상세 입력 화면에서 사용자가 앨범에 있는 사진을 다시 선택할수도 있으므로 '다시찍기' 보다는 '다시 가져오기' 나 다른 문구가 좋을것 같습니다!

@rohi404 디자인에서는 아이콘으로 들어갈것 같아서 이전 사진 설정 부분으로 가지면 될것 같아요! 아마 아이콘으로 대체될 것 같아요!

**Comment by bb-grizzle** [comment]
@yurim22 이미지 확인하는 과정을 넣자는 말씀이시지죠?

**Comment by chayeoi** [comment]
@bb-grizzle 이미지 위에 '다시' 버튼을 클릭햇을 땐 어떤 액션이 발생하는건가요~?

**Comment by chayeoi** [comment]
@bb-grizzle 이번 스프린트 종료까지 4일밖에 남지 않아서, 우선은 지금 와이어프레임대로 디자인 작업해주시고 논의가 필요한 부분은 작업해주신 내용 바탕으로 다시 하도록 하죠~
이 이슈는 우선 close하겠습니다.

**Comment by bb-grizzle** [comment]
@chayeoi 네 알겠습니다!
