### ISSUE TITLE
와이어프레임-상세보기/메뉴

### ISSUE THREAD

**Issue by bb-grizzle** [mash-up-kr/luvket#25]
상세보기에서 메뉴를 탭했을 때 수정, 삭제 할 수 있다.

메뉴: https://zpl.io/blA80mX
삭제: https://zpl.io/brpYQr7

**Comment by jus0k** [comment]
메뉴를 눌렀을 때의 화면(list_detail_menu)과 삭제 하시겠습니까? 화면 (list_detail_menu_delete)는 화면의 컨텍스트가 다른데 동일한 형태로 되어 있어서 명확하지 않은 것 같다는 생각이 듭니다. 삭제 하시겠습니까? 화면은 Dialog의 형태로 가는건 어떨까요? 
https://material.io/components/dialogs/
https://material.io/components/sheets-bottom/

**Comment by rohi404** [comment]
'삭제 하시겠습니까?' 문구는 따로 알림 창이 떠서 선택하게 했으면 좋겠습니다.

**Comment by bb-grizzle** [comment]
@jus0k @rohi404 
페이스북의 삭제를 참고했는데 저런식으로 되어있더라고요. 인스타는 두분이 말씀하신 대로 이후 확인은 팝업으로 되어 있긴 합니다. 
추가적으로 요즘 계속해서 스마트폰이 커지고 있고 그래서 다이얼로그로 줄시 사용성이 편하진 않다는 추세라 아래에서 나타나도록 만들었어요. 
확인해주시고 다시 리뷰 주세요! 

![IMG_5370](https://user-images.githubusercontent.com/26290562/69475893-2d483e00-0e16-11ea-9fec-1ed7b4a03683.PNG)
![IMG_5371](https://user-images.githubusercontent.com/26290562/69475894-2de0d480-0e16-11ea-97bd-c62e4bc1b270.PNG)

**Comment by vo0a** [comment]
이상없습니다.
