### ISSUE TITLE
와이어프레임-일정/추가하기

### ISSUE THREAD

**Issue by bb-grizzle** [mash-up-kr/luvket#27]
일정 추가 버튼을 통해 일정을 추가할 수 있다.

만들어져 있는 리스트를 선택해서 하루의 일정을 만들 수 있다.

https://zpl.io/bzRkoWX

**Comment by rohi404** [comment]
리스트에 있는 + 플로팅 버튼과 일정 추가에 있는 +  플로팅 버튼이 동일하게 생겨서 사용자가 헷갈릴 수 있을 것 같아요.

**Comment by jus0k** [comment]
여기에 있는 검색에도 홈 화면에 있는 검색 필터 기능이 있어야 할 것 같습니다. 또 여러 개의 항목을 선택할 수 있는 것이라면, 현재 선택된 아이템을 확인할 수 있는 UI가 필요할 것 같다는 생각이 듭니다!

**Comment by rohi404** [comment]
기존에 등록되어 있던 일정 삭제도 가능한가요~?

**Comment by bb-grizzle** [comment]
@rohi404 현제는 같은 아이콘으로 통일 되어 있는데 작업할때는 다르게 할 것 같아요!

**Comment by bb-grizzle** [comment]
@rohi404 가능해야 할 것 같아요! 여기도 홈에 있는 편집 추가하도록 할게요!

**Comment by bb-grizzle** [comment]
@jus0k 수정했습니다!

**Comment by vo0a** [comment]
이상없습니다.
