### ISSUE TITLE
디자인-로그인

### ISSUE THREAD

**Issue by bb-grizzle** [mash-up-kr/luvket#31]
디자인-로그인 입니다. 

https://zpl.io/VOnNwEl

**Comment by rohi404** [comment]
이상 없습니다!

**Comment by chayeoi** [comment]
hover, focus, active 스타일에 대한 가이드가 함께 추가되면 좋을 것 같습니다~

**Comment by chayeoi** [comment]
로고에 사용된 폰트가 필기체로 적혀있어서 읽기 어렵네요~ luvket 영문 표기 자체도 어떻게 읽어야 할지 사용자가 판단하기 쉽지 않아서 다른 서체를 사용하면 좋을 것 같습니다~ 😄

**Comment by jus0k** [comment]
<img width="334" alt="스크린샷 2019-11-24 오전 12 51 13" src="https://user-images.githubusercontent.com/43605468/69481469-fa716a80-0e54-11ea-90c7-b75cf8447d7c.png">

카카오 버튼이 카카오 버튼인지 알기가 어려운 것 같아요! 카카오에서 제공하는 버튼 타입에 있는 어두운 심볼을 사용하는게 어떨까 하는 생각이 듭니다.
https://developers.kakao.com/buttons

**Comment by chayeoi** [comment]
화면 전체적으로 빈 공간이 많은데, 버튼의 높이를 늘려서 버튼 선택 영역을 넓혀주는 건 어떨까요?

**Comment by chayeoi** [comment]
제플린에 코멘트 남겨놓았습니다~ 확인 부탁드려요!

**Comment by bb-grizzle** [comment]
> <img alt="스크린샷 2019-11-24 오전 12 51 13" width="334" src="https://user-images.githubusercontent.com/43605468/69481469-fa716a80-0e54-11ea-90c7-b75cf8447d7c.png">
> 
> 카카오 버튼이 카카오 버튼인지 알기가 어려운 것 같아요! 카카오에서 제공하는 버튼 타입에 있는 어두운 심볼을 사용하는게 어떨까 하는 생각이 듭니다.
> https://developers.kakao.com/buttons

@jus0k 반영하겠심!

**Comment by bb-grizzle** [comment]
> 화면 전체적으로 빈 공간이 많은데, 버튼의 높이를 늘려서 버튼 선택 영역을 넓혀주는 건 어떨까요?

@chayeoi 화면 빈 부분을 지금은 어찌 하기 힘들지만 나중에 일러스트나 페턴으로 채워주면 좋을 것 같아요!
