### ISSUE TITLE
디자인-홈/오늘일정

### ISSUE THREAD

**Issue by bb-grizzle** [mash-up-kr/luvket#43]
오늘 일정이 있을 때 알려줍니다.

https://zpl.io/VKLGgAW

**Comment by jus0k** [comment]
숨기기, 확인 버튼은 상하좌우 여백을 주신 것 같은데 시각적으로 보기에 균형이 안맞는 것 같다는 생각이 쪼금 듭니다! 메세지에 좌측, 상단 여백을 조금 더 주는건 어떨까요?

**Comment by rohi404** [comment]
확인 버튼을 누르면 어떻게 되나요~?

**Comment by bb-grizzle** [comment]
@jus0k 확실히 치우쳐진 느낌이 드네요. 수정해볼게요! 
@rohi404 일정 부분으로 페이지가 이동 됩니다!
